parameters:
#    php_bb_update_git_repo.example.class: phpBB\UpdateGitRepoBundle\Example

services:
#    php_bb_update_git_repo.example:
#        class: %php_bb_update_git_repo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
